site_name: GIRA Occupancy Modeling

theme:
  name: material

markdown_extensions:
  - attr_list
  - md_in_html

repo_name: 'gira3d/gira3d-occupancy-modeling'
repo_url: 'https://github.com/gira3d/gira3d-occupancy-modeling'

nav:
  - Home: 'index.md'
  - Occupancy Modeling Tutorials:
    - 'MATLAB' : 'tutorials/matlab/matlab.md'
    - 'Python' : 'tutorials/python/python.md'
